### ISSUE TITLE
problem with ms drift install

### ISSUE THREAD

**Issue by rtraghavan** [magland/msdrift#1]
I also am having trouble getting msdrift to work. I did the following,
1. I cloned the repo and created a symbolic link at /home/$user/anaconda3/envs/mountainsort/etc/mountainlab/packages.
2. I then tried to execute ml-list-processors and received the following error (see below).
Any idea of how to proceed

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/mountainsort/etc/mountainlab/packages/msdrift/python/drift.py", line 12, in <module>
    import p_join_segments
  File "/data/user/repos/labMS4/msdrift/python/p_join_segments.py", line 8, in <module>
    from basic.p_compute_templates import compute_templates_helper
  File "/home/user/anaconda3/envs/mlab/etc/mountainlab/packages/ml_pyms/basic/__init__.py", line 6, in <module>
    from .p_bandpass_filter import * 
  File "/home/user/anaconda3/envs/mlab/etc/mountainlab/packages/ml_pyms/basic/p_bandpass_filter.py", line 16, in <module>
    import bandpass_filter_cpp as cpp
ImportError: /home/user/anaconda3/envs/mountainsort/lib/python3.6/site-packages/bandpass_filter_cpp.cpython-36m-x86_64-linux-gnu.so: undefined symbol: GOMP_parallel

**Comment by vjtiznado** [comment]
Hi, could you solve the problem? I have exactly the same issue. I just installed mountainsort on my Mac following the updated instructions and after that I tried to add msdrift and I got this. I have to say that one month ago I successfully added msdrift on a linux machine, and following the same steps now I couldn't. I don't know if something was changed since or if is it a Mac issue
